[build]
  command = "npm run build"
  publish = "out"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "netlify/functions"
